version: "2.2"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:80"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8090:8080