version: "3.3"  # optional since v1.27.0
services:
  web:
    image: php:7.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
#    links:
#      - redis
 # redis:
#    image: redis
#volumes:
#  logvolume01: {}